remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: auto
  
title: Objectionable-C
author: Tim Johnsen

description: >
  Musings on iOS development by Tim Johnsen.

social_links:
  github: timonus
  stackoverflow: 3943258
