remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
minima:
  skin: solarized
  
title: Objectionable-C
author: Tim Johnsen

# description: >
#   Musings on iOS development by Tim Johnsen.

# social_links:
#   { platform: github, user_url: "https://github.com/timonus" }
#   { platform: stackoverflow, user_url: "https://stackoverflow.com/users/3943258" }
