baseURL = 'https://objectionable-c.com'
languageCode = 'en-us'
title = 'Objectionable-C'
theme = 'theme'

[params.author]
  avatar = "avatar.jpg" # put the file in assets folder; also ensure that image has same height and width
  # Note: image is not rendered if the resource(avatar image) is not found. No error is displayed.
  intro = "Objectionable-C"
  name = "Tim Johnsen"
  description = "Musings on iOS development"
  fediverseAccount = "@timonus@mastodon.social"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

[[params.socialIcons]]
name = "mastodon"
url = "https://mastodon.social/@timonus"

[[params.socialIcons]]
name = "github"
url = "https://github.com/timonus"

[[params.socialIcons]]
name = "rss"
url = "/index.xml"